import pathlib
import sbase as sb
from config import *
     
if __name__ == "__main__":
    script_directory = pathlib.Path().absolute()
    sb.option.add_experimental_option('excludeSwitches', ['enable-logging'])
    sb.option.add_argument(f"user-data-dir={script_directory}/profiles/p2")
    sb.driver = webdriver.Chrome(options=sb.option, desired_capabilities=sb.capabilities, executable_path = 'C:\git\cft\driver\chromedriver.exe')
    print('Started')
    sb.nw = datetime.now()
    
    while (sb.nw <= time_12_00):
        if (sb.nw >= time_10_30 and sb.nw <= time_11_00):
            #Buy after 10:30 systime or analyst recommended
            # ( {33489} ( ( {cash} ( ( ( ( 1 day ago close - 1 day ago open ) * 100 ) / 1 day ago close ) < 1.5 and ( [=1] 5 minute "close - 1 candle ago close / 1 candle ago close * 100" ) > -0.3 and ( [=2] 5 minute "close - 1 candle ago close / 1 candle ago close * 100" ) < 0.5 and [-1] 10 minute "close - 1 candle ago close / 1 candle ago close * 100" < 0.5 and [-2] 10 minute "close - 1 candle ago close / 1 candle ago close * 100" < 0.5 and [=1] 1 hour low < 1 day ago high and [=1] 5 minute volume > greatest(  1 day ago volume / 30  ) and ( ( ( [=1] 5 minute close - [=1] 5 minute open ) * 100 ) / 1 day ago close ) < 0 and 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" > -3 ) ) and ( {cash} ( ( ( ( [=1] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) < 1 and ( ( ( [=1] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) > 0 and ( ( ( [=1] 5 minute close - [=1] 5 minute open ) * 100 ) / 1 day ago close ) < 0.3 and ( ( ( [=1] 1 hour low - [=1] 5 minute low ) * 100 ) / 1 day ago close ) > -1 and 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" < 3 and [-1] 5 minute close > [=1] 5 minute high and [=2] 5 minute high < [-1] 5 minute high and [=2] 10 minute high < [-1] 5 minute high and [=2] 15 minute high < [-1] 5 minute high ) ) and ( {cash} ( [0] 5 minute high > [=-1] 3 hour high and [0] 5 minute high > [=2] 10 minute high and [0] 5 minute high > [=2] 15 minute high and [0] 5 minute high > [=3] 15 minute high and ( ( ( [=1] 5 minute open - [=1] 30 minute low ) * 100 ) / 1 day ago close ) < 1.5 and ( ( ( [=1] 5 minute close - [=1] 30 minute low ) * 100 ) / 1 day ago close ) < 1.5 and ( ( ( 1 day ago close - [=1] 30 minute low ) * 100 ) / 1 day ago close ) < 1 and ( ( ( [=1] 5 minute high - [=1] 5 minute low ) * 100 ) / 1 day ago close ) < 1.3 and ( ( ( [-1] 5 minute high - [=1] 5 minute low ) * 100 ) / 1 day ago close ) < 2.5 and ( ( ( [-1] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) > 1 and ( ( ( [=1] 5 minute low - [-2] 5 minute high ) * 100 ) / 1 day ago close ) > -1.7 ) ) ) )
            process_url_volBreakout('https://chartink.com/screener/morning-volume-breakout-buy-consolidation-01','buy-dayconsolidation-breakout-01', time_10_30, time_11_00)

        if (sb.nw >= time_10_00 and sb.nw <= time_11_00):
            # ( {33489} ( ( {cash} ( ( ( ( [=1] 5 minute high - [=1] 15 minute low ) * 100 ) / [=1] 5 minute open ) > 1 and ( ( ( [=1] 30 minute low - 1 day ago close ) * 100 ) / 1 day ago close ) < -0.3 and ( ( ( [=1] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) < 1 and 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" > 0 and 2 days ago "close - 1 candle ago close / 1 candle ago close * 100" < 2 and [-1] 5 minute high > [=1] 5 minute high and [-2] 5 minute high > [=1] 5 minute high and [=1] 30 minute low <= [=1] 15 minute low and [=1] 30 minute low <= [=1] 1 hour low and [=3] 15 minute high < [=1] 15 minute high and [=2] 5 minute high < [-1] 5 minute high and [=2] 10 minute high < [-1] 5 minute high and [=2] 15 minute high < [-1] 5 minute high and abs ( 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" ) > 0.75 ) ) ) )
            process_url_volBreakout('https://chartink.com/screener/buy-dayconsolidation-breakout-04', 'buy-dayconsolidation-breakout-02', time_10_00, time_11_00)

        if (sb.nw >= time_09_30 and sb.nw <= time_10_15):
            # ( {33489} ( ( {cash} ( ( ( ( [=1] 15 minute low - 1 day ago close ) * 100 ) / [=1] 5 minute open ) < -1 and ( ( ( [=1] 5 minute low - [=1] 15 minute open ) * 100 ) / [=1] 5 minute open ) < 0 and ( ( ( [-1] 5 minute close - [-3] 5 minute open ) * 100 ) / [=1] 5 minute open ) > 0.5 and ( [0] 5 minute high - [=1] 10 minute low ) > ( 1 day ago close - [0] 5 minute high ) and ( ( ( [-1] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) > -0.5 and ( ( ( 1 day ago close - [=-4] 2 hour low ) * 100 ) / 1 day ago close ) < 4 and ( ( ( 2 days ago close - [=-8] 1 hour low ) * 100 ) / 2 days ago close ) < 4 and [0] 5 minute close > [=3] 5 minute high and 2 days ago "close - 1 candle ago close / 1 candle ago close * 100" > -1.5 and 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" > -3.25 and [-1] 5 minute low > [=1] 15 minute low and [-2] 5 minute low > [=1] 15 minute low ) ) ) )
            process_url_volBreakout('https://chartink.com/screener/morning-volume-breakout-buy-consolidation-02', 'buy-dayconsolidation-breakout-03', time_09_30, time_10_00)

        if (sb.nw >= time_10_30 and sb.nw <= time_11_15):
            # after 10:30
            # ( {33489} ( ( {cash} ( [=1] 30 minute high > 1 day ago close and [=1] 5 minute low < 2 days ago high and [=1] 5 minute close > [=1] 5 minute open and [=2] 5 minute close > [=1] 5 minute open and [=2] 5 minute open > [=1] 5 minute open and ( ( ( [=1] 15 minute high - 1 day ago close ) * 100 ) / 1 day ago close ) > 0.75 and ( ( ( [=1] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) > 1 and ( ( ( [-1] 5 minute close - [=-1] 5 minute high ) * 100 ) / 1 day ago close ) > 1.2 and ( ( ( [-1] 5 minute close - [=1] 5 minute low ) * 100 ) / [=1] 5 minute open ) > 0.75 and ( ( ( 1 day ago close - 2 days ago close ) * 100 ) / 2 days ago close ) < 3 and ( ( ( 1 day ago close - 1 day ago open ) * 100 ) / 1 day ago close ) < 1.5 and ( ( ( 1 day ago close - 1 day ago open ) * 100 ) / 1 day ago close ) > -2 ) ) and ( {cash} ( ( ( ( [=1] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) < 4 and ( ( ( [-1] 5 minute high - [=1] 10 minute high ) * 100 ) / 1 day ago close ) < 0.7 and ( ( ( [=1] 5 minute open - [=1] 5 minute low ) * 100 ) / 1 day ago close ) < 0.3 and ( ( ( 1 day ago close - [=1] 5 minute low ) * 100 ) / 1 day ago close ) < 0.3 and [0] 5 minute high > 1 day ago high and [0] 15 minute "close - 1 candle ago close / 1 candle ago close * 100" > 0 ) ) ) )
            process_url_volBreakout('https://chartink.com/screener/buy-breakup-intraday-9-25-to-10-30-06', '1-Bbuyy-morningUp-downConsolidation', time_10_30, time_11_15)

        # Weekly High not reached, morning up consolidation and down, (high - current) LT (current - low)
        if (sb.nw >= time_10_00 and sb.nw <= time_10_30):
            # ( {33489} ( ( {cash} ( ( ( ( [0] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) > 1 and ( ( ( [=1] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close ) < 4 and ( ( ( [-1] 5 minute close - [=1] 5 minute open ) * 100 ) / 1 day ago close ) > 0.75 and ( ( ( weekly high - 1 day ago high ) * 100 ) / 1 day ago close ) > 0.5 and ( ( ( 1 week ago high - [=1] 5 minute high ) * 100 ) / 1 day ago close ) > 0 and ( ( ( 1 week ago high - 1 day ago high ) * 100 ) / 1 day ago close ) > 0 and ( [=1] 15 minute high - [-1] 5 minute high ) < ( [-1] 5 minute low - [=1] 15 minute low ) and ( ( ( [=2] 5 minute low - [-1] 30 minute low ) * 100 ) / 1 day ago close ) > 0.6 ) ) and ( {cash} ( [=1] 5 minute volume > greatest(  1 day ago volume / 30  ) and [=1] 10 minute volume > greatest(  1 day ago volume / 22  ) and [=1] 15 minute volume > greatest(  1 day ago volume / 15  ) and [=1] 30 minute high > [-1] 5 minute high and 1 day ago close < 2 days ago high and ( ( ( 1 day ago close - 1 day ago low ) * 100 ) / 1 day ago close ) < 2 and ( ( ( 2 days ago close - 2 days ago open ) * 100 ) / 1 day ago close ) < 2 ) ) ) )
            process_url_volBreakout('https://chartink.com/screener/buy-dayconsolidation-breakout-02', '0-Bbuyy-morningUp-downConsolidation', time_10_00, time_10_30)



        # if (sb.nw >= time_09_45 and sb.nw <= time_10_30):
        # ( {cash} ( ( {33489} ( [0] 5 minute high > [=-1] 3 hour high and [0] 5 minute high > [=2] 10 minute high and [0] 5 minute high > [=2] 15 minute high and [0] 5 minute high > [=3] 15 minute high and [=1] 30 minute high = [=1] 15 minute high and [=2] 15 minute low < [=1] 5 minute open and ( ( ( [=1] 5 minute open - [=1] 30 minute low ) * 100 ) / 1 day ago close ) < 1.5 and ( ( ( [=1] 5 minute close - [=1] 30 minute low ) * 100 ) / 1 day ago close ) < 1.5 and ( ( ( 1 day ago close - [=1] 30 minute low ) * 100 ) / 1 day ago close ) < 1.5 ) ) and ( {cash} ( [-1] 15 minute "close - 1 candle ago close / 1 candle ago close * 100" > 0 and [=1] 5 minute high < [=-1] 15 minute low ) ) ) )
        # process_url_volBreakout('https://chartink.com/screener/buy-dayconsolidation-breakout-03', 'buy-dayconsolidation-breakout-01', time_09_45, time_12_00)

        time.sleep(5)
        sb.nw = datetime.now()
        
    sb.driver.quit()
    