import sbase as sb
from config import *
     
if __name__ == "__main__":
    sb.option.add_argument("user-data-dir=/Users/profilechrome/profiles/p5")
    sb.option.add_argument('--headless')
    sb.driver = webdriver.Chrome(options=sb.option, desired_capabilities=sb.capabilities)
    print('Started')
    sb.nw = datetime.now()

    while (sb.nw <= time_11_00):
        if (sb.nw >= time_09_30 and sb.nw <= time_11_00):
            # ( {33489} ( ( {cash} ( [0] 5 minute low < [=1] 10 minute low and [-1] 5 minute low < 1 day ago low and [-1] 5 minute low < 2 days ago low and [-1] 5 minute low < 3 days ago low and [-3] 5 minute high > 1 day ago low and [-3] 5 minute high > 2 days ago low and [-3] 5 minute high > 3 days ago low and 1 day ago high > 4 days ago low and 1 day ago high > 5 days ago low and 1 day ago high > 6 days ago low and abs ( 1 day ago close - 10 days ago open ) * 100 / 1 day ago close > 3 and abs ( 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" ) < 1 and abs ( 1 day ago close - 1 day ago open * 100 ) / 1 day ago close < 1.3 and abs ( 2 days ago close - 2 days ago open * 100 ) / 2 days ago close < 1.3 ) ) ) )
            process_url('https://chartink.com/screener/supertrend-morning-sell', 'sell-consolidation-3day', time_09_30, time_11_00)

        #if(sb.nw>=time_09_25 and sb.nw<=time_10_15):
            #( {cash} ( 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" > 0 and 2 days ago "close - 1 candle ago close / 1 candle ago close * 100" > -0.5 and ( ( 1 day ago close - 1 day ago open ) * 100 ) / 1 day ago open > 2 and ( ( 2 days ago close - 2 days ago open ) * 100 ) / 2 days ago open > 2 and ( ( 1 day ago close - 3 days ago close ) * 100 ) / 3 days ago close > 5 and ( ( 1 day ago close - 2 days ago open ) * 100 ) / 2 days ago open > 3 and [=3] 5 minute close < [=1] 5 minute close and [=1] 30 minute low < 1 day ago high and ( ( [=1] 5 minute close - [=1] 5 minute open ) * 100 ) / [=1] 5 minute open < 0.4 and ( ( [=1] 10 minute close - [=1] 10 minute open ) * 100 ) / [=1] 5 minute open < -0.7 and ( ( [0] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close > -1 and [-1] 5 minute low < [=1] 5 minute low and [=1] 5 minute vwap > [=3] 5 minute vwap and [=2] 5 minute vwap > [=3] 5 minute vwap and [-1] 5 minute close < [-1] 5 minute vwap ) ) 
            #process_url('https://chartink.com/screener/sell-uptrend-01', 'sell-uplast2day)', time_09_25, time_10_00) 
            #( {cash} ( 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" < 0 and 2 days ago "close - 1 candle ago close / 1 candle ago close * 100" < 0.5 and ( ( 1 day ago close - 1 day ago open ) * 100 ) / 1 day ago open < -2 and ( ( 2 days ago close - 2 days ago open ) * 100 ) / 2 days ago open < -2 and ( ( 1 day ago close - 3 days ago close ) * 100 ) / 3 days ago close < -5 and ( ( 1 day ago close - 2 days ago open ) * 100 ) / 2 days ago open < -3 and [=3] 5 minute close > [=1] 5 minute close and [=1] 30 minute high > 1 day ago low and ( ( [=1] 5 minute close - [=1] 5 minute open ) * 100 ) / [=1] 5 minute open > -0.5 and ( ( [=1] 10 minute close - [=1] 10 minute open ) * 100 ) / [=1] 10 minute open > 0.7 and ( ( [0] 5 minute close - 1 day ago close ) * 100 ) / 1 day ago close < 1 and [-1] 5 minute high > [=1] 5 minute high and [=1] 5 minute vwap < [=3] 5 minute vwap and [=2] 5 minute vwap < [=3] 5 minute vwap and [-1] 5 minute close > [-1] 5 minute vwap ) ) 
            #process_url('https://chartink.com/screener/buy-downtrend-01', 'sell-downlast2day)', time_09_25, time_10_15)
            

        #if(sb.nw>=time_09_30 and sb.nw<=time_12_00):
            #( {33489} ( ( {33489} ( [=1] 30 minute high > latest "( (1 candle ago high + 1 candle ago low + 1 candle ago close / 3 ) * 2 - 1 candle ago low )" and [-3] 5 minute high < [-3] 5 minute ema ( [-3] 5 minute close , 100 ) and [-1] 5 minute high < [-1] 5 minute ema ( [-1] 5 minute close , 100 ) and [-1] 5 minute high < [-1] 5 minute vwap and [-1] 5 minute high > latest "(1 candle ago high + 1 candle ago low + 1 candle ago close / 3)" and [-1] 15 minute "close - 1 candle ago close / 1 candle ago close * 100" < 0 and ( ( ( [=1] 5 minute high - 1 day ago close ) * 100 ) / 1 day ago close ) > -0.2 and ( ( ( [0] 5 minute low - [=1] 5 minute open ) * 100 ) / [=1] 5 minute open ) < -0.3 and ( ( ( [0] 5 minute low - [=1] 5 minute close ) * 100 ) / [=1] 5 minute close ) < -0.3 and ( ( ( 1 day ago low - 2 days ago high ) * 100 ) / 2 days ago high ) > -7 and 2 days ago "close - 1 candle ago close / 1 candle ago close * 100" < 1.5 and 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" < 1 ) ) ) ) 
            #process_url('https://chartink.com/screener/sell-ema-down0', 'sell-ema-down0', time_10_00, time_12_00)
        #if (sb.nw >= time_10_30 and sb.nw <= time_13_15):
            #( {cash} ( ( latest "( (1 candle ago high + 1 candle ago low + 1 candle ago close / 3 ) * 2 - 1 candle ago high)" - [=1] 15 minute low ) > ( [=1] 15 minute low - latest "(1 candle ago high + 1 candle ago low + 1 candle ago close / 3)" ) and ( latest "( (1 candle ago high + 1 candle ago low + 1 candle ago close / 3 ) * 2 - 1 candle ago low )" - [-1] 5 minute low ) > ( [-1] 5 minute low - latest "(1 candle ago high + 1 candle ago low + 1 candle ago close / 3)" ) and [=1] 1 hour high > [=1] 15 minute high and [=1] 2 hour high > latest "( (1 candle ago high + 1 candle ago low + 1 candle ago close / 3 ) * 2 - 1 candle ago low )" and [-1] 5 minute low < latest "(1 candle ago high + 1 candle ago low + 1 candle ago close / 3)" and 1 day ago "close - 1 candle ago close / 1 candle ago close * 100" < -0.5 and 2 days ago "close - 1 candle ago close / 1 candle ago close * 100" < -0.5 and ( latest "( (1 candle ago high + 1 candle ago low + 1 candle ago close / 3 ) * 2 - 1 candle ago low )" - latest "( (1 candle ago high + 1 candle ago low + 1 candle ago close / 3 ) * 2 - 1 candle ago high)" ) * 100 / latest "( (1 candle ago high + 1 candle ago low + 1 candle ago close / 3 ) * 2 - 1 candle ago high)" > 2 ) ) 
            #process_url('https://chartink.com/screener/sell-ema-down1', 'sell-ema-down1', time_10_30, time_13_15)
        
        if(sb.nw>= time_09_35 and sb.nw <= time_10_45):
            #( {cash} ( [=1] 5 minute open < 1 day ago high and [=1] 5 minute close < 1 day ago high and [-1] 5 minute low <= [-2] 15 minute low and [-1] 5 minute low <= [-3] 15 minute low and [-1] 5 minute low < [=1] 15 minute low and ( ( [-1] 5 minute low - [=1] 5 minute low ) * 100 ) / [=1] 5 minute low < -0.3 and ( ( [-1] 5 minute close - [=-1] 5 minute close ) * 100 ) / [=-1] 5 minute close < -0.3 and ( ( [-1] 5 minute close - [=-1] 5 minute close ) * 100 ) / [=-1] 5 minute close > -2.5 and ( ( [-1] 5 minute low - [=1] 5 minute low ) * 100 ) / [=1] 5 minute low > -2.5 and ( ( 1 day ago close - 1 day ago open ) * 100 ) / 1 day ago open > -3 and ( ( 1 day ago low - 1 day ago open ) * 100 ) / 1 day ago low > -4 and ( ( 1 day ago low - 1 day ago high ) * 100 ) / 1 day ago high > -5 and ( ( [=-3] 15 minute close - 1 day ago open ) * 100 ) / 1 day ago open < -1 and ( ( 1 day ago low - [=-12] 30 minute low ) * 100 ) / [=-12] 30 minute low < -1 and ( ( [=-3] 15 minute low - 2 days ago close ) * 100 ) / 2 days ago close < -1 and ( ( [=-2] 1 hour low - 2 days ago close ) * 100 ) / 2 days ago close < -1.5 and [-1] 5 minute high < [-1] 5 minute vwap and [-2] 5 minute high < [-2] 5 minute vwap and ( ( [-2] 5 minute high - [-1] 5 minute low ) * 100 ) / [-2] 5 minute high > -0.5 and ( ( [-1] 5 minute high - [0] 5 minute low ) * 100 ) / [-1] 5 minute high > -0.5 ) ) 
            process_url('https://chartink.com/screener/sell-breakdown-intraday-9-30-to-10-3', 'sell-(=========DOWNTREND=======)breakdown-intraday-9:40-to-10:10-01', time_09_35, time_10_00, True)
            #( {cash} ( [=1] 5 minute open < 1 day ago high and [=1] 5 minute close < 1 day ago high and [-1] 5 minute low <= [-2] 15 minute low and [-1] 5 minute low < [=1] 15 minute low and ( ( [-1] 5 minute close - [=-1] 5 minute close ) * 100 ) / [=-1] 5 minute close > -2.5 and ( ( [-1] 5 minute low - [=1] 5 minute low ) * 100 ) / [=1] 5 minute low > -2.5 and ( ( 1 day ago close - 1 day ago open ) * 100 ) / 1 day ago open > -2 and ( ( 1 day ago close - 2 days ago open ) * 100 ) / 2 days ago open > -3 and ( ( 1 day ago close - 3 days ago close ) * 100 ) / 3 days ago close > -3 and ( ( 1 day ago low - 1 day ago open ) * 100 ) / 1 day ago low > -4 and ( ( 1 day ago low - 1 day ago high ) * 100 ) / 1 day ago high > -5 and ( ( [=-3] 15 minute close - 1 day ago open ) * 100 ) / 1 day ago open < -1 and ( ( 1 day ago low - [=-12] 30 minute low ) * 100 ) / [=-12] 30 minute low < -1 and ( ( [=-3] 15 minute low - 2 days ago close ) * 100 ) / 2 days ago close < -1 and ( ( [=-2] 1 hour low - 2 days ago close ) * 100 ) / 2 days ago close < -1.5 and [0] 5 minute low < 1 day ago low and [-1] 5 minute high < [-1] 5 minute vwap and [-2] 5 minute high < [-2] 5 minute vwap and ( ( [-2] 5 minute high - [-1] 5 minute low ) * 100 ) / [-2] 5 minute high > -0.5 and ( ( [-1] 5 minute high - [0] 5 minute low ) * 100 ) / [-1] 5 minute high > -0.5 ) ) 
            process_url('https://chartink.com/screener/sell-breakdown-intraday-9-50-to-10-10-01', 'sell-(=========DOWNTREND=======)breakdown-intraday-9:40-to-10:10-01', time_09_35, time_10_00, True)
            
        #time.sleep(10)
        sb.nw = datetime.now()
        
    sb.driver.quit()
    