pyenv global system
pyenv local system
python ./technical.py all
pyenv global 3.5.0
pyenv local 3.5.0
python ./classifier.py all
python ./regression.py all
python ./result.py all
pyenv global system
pyenv local system
